# 手撕Promise

## 1.1、实现一个基本版本Promise

要求：创建一个构造函数Promise，创建一个Promise类，在使用的时候传入了一个执行器executor，executor会传入两个参数：成功(resolve)和失败(reject)。

作答：

```js
// 阶段1:
// 三种状态： pending、fulfilled、rejected
// 状态改变后不可变
// pending -> fulfilled 且必须有一个不可改变的值(value)
// pending -> rejected 且必须又一个不可改变的理由(reason)
// new Promise((resolve, reject) => { resolve(value) }) resolve为成功，接收value，状态改为 fulfilled
// new Promise((resolve, reject) => { reject(value) }) reject为失败，接收reason，状态改为 rejected
// executor报错则执行reject()

class _Promise {
  constructor(executor) {
    // 初始状态
    this.status = 'pending'
    // 初始状态中成功值
    this.value = undefined
    // 初始状态中失败理由
    this.reason = undefined
    // 定义 resolve 方法，接收 value 并完成赋值
    // 将状态从 pending 改为 fulfilled
    let _resolve = (value) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'fulfilled'
        this.value = value;
      }
    }
    // 定义 reject 方法，接收 reason 并完成赋值
    // 将状态从 pending 改为 rejected
    let _reject = (reason) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'rejected'
        this.reason = reason
      }
    }
    // 执行传入的方法
    try {
      executor(_resolve, _reject)
    } catch (error) {
      // 在 executor 执行失败时调用 reject 方法
      _reject(error)
    }
  }
}
```

## 1.2、实现一个带then的Promise

要求：基于1.1中的Promise，实现then方法，then方法支持链式调用。

作答：

```js
// 阶段2:
// 标准规定 then 接收两个参数 onFulfilled、onRejected
// Promise 的 state 变更为 fulfilled 时执行 onFulfilled，并将 value 传入
// Promise 的 state 变更为 rejected 时执行 onRejected，并将 reason 传入
class _Promise {
  constructor(executor) {
    // 初始状态
    this.status = 'pending'
    // 初始状态中成功值
    this.value = undefined
    // 初始状态中失败理由
    this.reason = undefined
    // 定义 resolve 方法，接收 value 并完成赋值
    // 将状态从 pending 改为 fulfilled
    let _resolve = (value) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'fulfilled'
        this.value = value;
      }
    }
    // 定义 reject 方法，接收 reason 并完成赋值
    // 将状态从 pending 改为 rejected
    let _reject = (reason) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'rejected'
        this.reason = reason
      }
    }
    // 执行传入的方法
    try {
      executor(_resolve, _reject)
    } catch (error) {
      // 在 executor 执行失败时调用 reject 方法
      _reject(error)
    }
  }

  // then 接受两个参数 onFulfilled、onRejected
  then(onFulfilled, onRejected) {
    // 状态为 fulfilled 的时候，执行 onFulfilled 方法，并且传递 value
    if (this.status === 'fulfilled') {
      onFulfilled(this.value)
    }
    // 状态为 rejected 的时候，执行 onRejected 方法，并且传递 reason
    if (this.status === 'rejected') {
      onRejected(this.reason)
    }
  }
}
```

```js
// 阶段3:
// 需要兼容 promise 的多次调用:
// const p = new Promise(resolve => {}, reject => {})
// p.then(onFulfilled1, onRejected1)
// p.then(onFulfilled2, onRejected2)
// p.then(onFulfilled3, onRejected3)
// 需要兼容 promise 中异步处理:
// new Promise(resolve => { setTimeout(() => { resolve(1) },0).then(resp => console.log(resp))

class Promise {
  constructor(executor) {
    // 初始状态
    this.status = 'pending'
    // 初始状态中成功值
    this.value = undefined
    // 初始状态中失败理由
    this.reason = undefined

    // 为了兼容 promise 的多次调用
    // 增加 onFulfilled 的回调函数队列
    this.onFulfilledCallbacks = []
    // 增加 onRejected 的回调函数队列
    this.onRejectedCallbacks = []

    // 定义 resolve 方法，接收 value 并完成赋值
    // 将状态从 pending 改为 fulfilled
    let _resolve = (value) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'fulfilled'
        this.value = value;
        // 在状态变更后执行 onFulfilled 回调函数队列
        this.onFulfilledCallbacks.forEach(fn => fn())
        // 执行完成后清空队列
        this.onFulfilledCallbacks = []
      }
    }
    // 定义 reject 方法，接收 reason 并完成赋值
    // 将状态从 pending 改为 rejected
    let _reject = (reason) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'rejected'
        this.reason = reason
        // 在状态变更后执行 onRejected 回调函数队列
        this.onRejectedCallbacks.forEach(fn => fn())
        // 执行完成后清空队列
        this.onRejectedCallbacks = []
      }
    }
    // 执行传入的方法
    try {
      executor(_resolve, _reject)
    } catch (error) {
      // 在 executor 执行失败时调用 reject 方法
      _reject(error)
    }
  }

  // then 接受两个参数 onFulfilled、onRejected
  then(onFulfilled, onRejected) {
    // 状态为 fulfilled 的时候，执行 onFulfilled 方法，并且传递 value
    if (this.status === 'fulfilled') {
      onFulfilled(this.value)
    }
    // 状态为 rejected 的时候，执行 onRejected 方法，并且传递 reason
    if (this.status === 'rejected') {
      onRejected(this.reason)
    }
    // 为了处理 promise 的异步处理
    // 所以这里将对应的参数全部存入队列中
    // 等 promise 的状态变更时再执行
    // 状态变更就是执行 _reject 和 _resolve 的时候
    if (this.status === 'pending') {
      // onFulfilled 存入 onFulfilledCallbacks 队列
      this.onFulfilledCallbacks.push(() => {
        onFulfilled(this.value)
      })
      // onRejected 存入 onRejectedCallbacks 队列
      this.onRejectedCallbacks.push(() => {
        onRejected(this.reason)
      })
    }
  }
}
```

```js
// 阶段4:
// 规范中要求 then 返回一个新的 promise
// 新的 promise 被称为 promise2:
// promise2 = promise1.then(onFulfilled, onRejected)
// 规范规定 onFulfilled() 或 onRejected() 的值，即第一个then返回的值，叫做 x
// 判断 x 的函数叫做 resolvePromise

class Promise {
  constructor(executor) {
    // 初始状态
    this.status = 'pending'
    // 初始状态中成功值
    this.value = undefined
    // 初始状态中失败理由
    this.reason = undefined

    // 为了兼容 promise 的多次调用
    // 增加 onFulfilled 的回调函数队列
    this.onFulfilledCallbacks = []
    // 增加 onRejected 的回调函数队列
    this.onRejectedCallbacks = []

    // 定义 resolve 方法，接收 value 并完成赋值
    // 将状态从 pending 改为 fulfilled
    let _resolve = (value) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'fulfilled'
        this.value = value;
        // 在状态变更后执行 onFulfilled 回调函数队列
        this.onFulfilledCallbacks.forEach(fn => fn())
        // 执行完成后清空队列
        this.onFulfilledCallbacks = []
      }
    }
    // 定义 reject 方法，接收 reason 并完成赋值
    // 将状态从 pending 改为 rejected
    let _reject = (reason) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'rejected'
        this.reason = reason
        // 在状态变更后执行 onRejected 回调函数队列
        this.onRejectedCallbacks.forEach(fn => fn())
        // 执行完成后清空队列
        this.onRejectedCallbacks = []
      }
    }
    // 执行传入的方法
    try {
      executor(_resolve, _reject)
    } catch (error) {
      // 在 executor 执行失败时调用 reject 方法
      _reject(error)
    }
  }

  // then 接受两个参数 onFulfilled、onRejected
  then(onFulfilled, onRejected) {
    // 状态为 fulfilled 的时候，执行 onFulfilled 方法，并且传递 value
    // if (this.status === 'fulfilled') {
    //   onFulfilled(this.value)
    // }
    // 状态为 rejected 的时候，执行 onRejected 方法，并且传递 reason
    // if (this.status === 'rejected') {
    //   onRejected(this.reason)
    // }
    // 为了处理 promise 的异步处理
    // 所以这里将对应的参数全部存入队列中
    // 等 promise 的状态变更时再执行
    // 状态变更就是执行 _reject 和 _resolve 的时候
    // if (this.status === 'pending') {
    //   // onFulfilled 存入 onFulfilledCallbacks 队列
    //   this.onFulfilledCallbacks.push(() => {
    //     onFulfilled(this.value)
    //   })
    //   // onRejected 存入 onRejectedCallbacks 队列
    //   this.onRejectedCallbacks.push(() => {
    //     onRejected(this.reason)
    //   })
    // }

    // onFulfilled onRejected 是可选参数
    // 规范要求 onFulfilled onRejected 不能同步调用

    // onFulfilled 如果不是函数，就直接返回value
    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value
    // onFulfilled 如果不是函数，就直接扔出错误
    // 如果不 throw 错误，而是 value => value
    // 会跑到下一个 then 中的 onFulfilled 中
    onRejected = typeof onRejected === 'function' ? onRejected : error => { throw error }

    // 这里创建 promise2
    // promise2 接收 resolve, reject
    let promise2 = new Promise((resolve, reject) => {
      // 状态为 fulfilled 的时候，执行 onFulfilled 方法，并且传递 value
      if (this.status === 'fulfilled') {
        // 因为要求异步调用，这里采用 setTimeout 的形式异步处理
        setTimeout(() => {
          // 这里声明 x 用于表示 onFulfilled 的返回值
          let x = onFulfilled(this.value)
          // 处理 return 的 promise 和默认的 promise2 的关系
          resolvePromise(promise2, x, resolve, reject)
        }, 0)
      }
      // 状态为 rejected 的时候，执行 onRejected 方法，并且传递 reason
      if (this.status === 'rejected') {
        // 因为要求异步调用，这里采用 setTimeout 的形式异步处理
        setTimeout(() => {
          // 这里声明 x 用于表示 onRejected 的返回值
          let x = onRejected(this.reason)
          // 处理 return 的 promise 和默认的 promise2 的关系
          resolvePromise(promise2, x, resolve, reject)
        }, 0)
      }
      // 为了处理 promise 的异步处理
      // 所以这里将对应的参数全部存入队列中
      // 等 promise 的状态变更时再执行
      // 状态变更就是执行 _reject 和 _resolve 的时候
      if (this.status === 'pending') {
        // onFulfilled 存入 onFulfilledCallbacks 队列
        this.onFulfilledCallbacks.push(() => {
          // 因为要求异步调用，这里采用 setTimeout 的形式异步处理
          setTimeout(() => {
            // 这里声明 x 用于表示 onFulfilled 的返回值
            let x = onFulfilled(this.value)
            // 处理 return 的 promise 和默认的 promise2 的关系
            resolvePromise(promise2, x, resolve, reject)
          }, 0)
        })
        // onRejected 存入 onRejectedCallbacks 队列
        this.onRejectedCallbacks.push(() => {
          // 因为要求异步调用，这里采用 setTimeout 的形式异步处理
          setTimeout(() => {
            // 这里声明 x 用于表示 onRejected 的返回值
            let x = onRejected(this.reason)
            // 处理 return 的 promise 和默认的 promise2 的关系
            resolvePromise(promise2, x, resolve, reject)
          }, 0)
        })
      }
    })
    // then 返回 promise2
    return promise2
  }
}

// resolvePromise 函数
// 处理 return 的 promise 和默认的 promise2 的关系
// 让不同的 promise 代码互相套用
function resolvePromise (promise2, x, resolve, reject) {
  // 在这里要判定 x 是不是一个 promise
  // 如果 x 是 promise，则执行 x，用执行后的结果来做 promise2 的结果
  // 如果 x 不是 promise，则用 x 做 promise2 的结果
  // 其中 resolve reject 是 promise2 的 resolve reject

  // 在判断 x 是不是 promise 之前，先判断 x 和 promise2 是否是同一个对象
  // 如果是同一个对象，则要报错，用于解决循环引用的问题
  if (x === promise2) {
    return reject(new TypeError('循环引用'))
  }
  // used 用于防止多次调用
  let used = false;
  // 判断 x 是不是 null
  const notNull = x !== null
  // 判断 x 是不是 object 或者 function
  const isObjectOrFuc =
      typeof x === 'object' ||
      typeof x === 'function'
  if (notNull && isObjectOrFuc) {
    // x 不是 null 且 x 是 object 或者 function
    try {
      // 获取 x 的 then，用于判定是否是一个 promise
      let then = x.then
      if (typeof then === 'function') {
        // 如果 then 的类型是 function 则认为 then 是 promise
        // 接着执行 then 方法，并且使用 call 方法
        // 将 then 的 this 指向 x
        then.call(x, value => {
          // 这里是成功的回调函数
          // value 是成功的结果
          // 如果多次调用直接返回
          if (used) return
          // 执行成功回调后，将 used 设置为true，解决多次调用问题
          used = true
          // 如果 value 还可能是 promise 怎么办
          // 继续执行 resolvePromise
          // 目的是处理 resolve 的结果依旧是 promise 的问题
          // 直到 resolve 的结果既不是 object 也不是 function
          resolvePromise(promise2, value, resolve, reject)
        }, reason => {
          // 这里是错误的回调函数
          // reason 是错误的原因
          // 如果多次调用直接返回
          if (used) return
          // 执行成功回调后，将 used 设置为true，解决多次调用问题
          used = true
          // 执行错误后抛出错误
          // 不需要在判断类型了
          reject(reason)
        })
      } else {
        // then 不是 function 则直接返回 x 作为 promise2 的结果
        resolve(x)
      }
    } catch (e) {
      // 如果出现重复调用直接返回
      if (used) return
      // 进入 catch 也算执行完成
      used = true
      // 把错误通过 reject 返回
      reject(e)
    }
  } else {
    // 其他的所有情况，直接返回 x
    resolve(x)
  }
}
```

```
// 阶段5:
// then 在阶段4里面使用 setTimout 来实现异步
// 这里也可以使用 Promise.resolve() 来实现异步
// 具体的 Promise.resolve() 实现见下一阶段

Promise.resolve().then(() => {
  // 这里声明 x 用于表示 onFulfilled 的返回值
  let x = onFulfilled(this.value)
  // 处理 return 的 promise 和默认的 promise2 的关系
  resolvePromise(promise2, x, resolve, reject)
})
```

## 1.3、实现完整版的Promise

要求：基于1.2中的Promise，实现完整版的Promise，实现all、race、resolve、reject、defer方法，可以通过promise A+规范检测

如何检测Promise是否正确：

```bash
npm i promises-aplus-tests -g
promises-aplus-tests [js文件名]

// https://promisesaplus.com/
```

作答：

```js
// 阶段6:
// 实现 catch、resolve、reject、finally、all、any、race 方法
// 可以通过promise A+规范检测

// resolvePromise 函数
// 处理 return 的 promise 和默认的 promise2 的关系
// 让不同的 promise 代码互相套用
function resolvePromise (promise2, x, resolve, reject) {
  // 在这里要判定 x 是不是一个 promise
  // 如果 x 是 promise，则执行 x，用执行后的结果来做 promise2 的结果
  // 如果 x 不是 promise，则用 x 做 promise2 的结果
  // 其中 resolve reject 是 promise2 的 resolve reject

  // 在判断 x 是不是 promise 之前，先判断 x 和 promise2 是否是同一个对象
  // 如果是同一个对象，则要报错，用于解决循环引用的问题
  if (x === promise2) {
    return reject(new TypeError('循环引用'))
  }
  // used 用于防止多次调用
  let used = false;
  // 判断 x 是不是 null
  const notNull = x !== null
  // 判断 x 是不是 object 或者 function
  const isObjectOrFuc =
    typeof x === 'object' ||
    typeof x === 'function'
  if (notNull && isObjectOrFuc) {
    // x 不是 null 且 x 是 object 或者 function
    try {
      // 获取 x 的 then，用于判定是否是一个 promise
      let then = x.then
      if (typeof then === 'function') {
        // 如果 then 的类型是 function 则认为 then 是 promise
        // 接着执行 then 方法，并且使用 call 方法
        // 将 then 的 this 指向 x
        then.call(x, value => {
          // 这里是成功的回调函数
          // value 是成功的结果
          // 如果多次调用直接返回
          if (used) return
          // 执行成功回调后，将 used 设置为true，解决多次调用问题
          used = true
          // 如果 value 还可能是 promise 怎么办
          // 继续执行 resolvePromise
          // 目的是处理 resolve 的结果依旧是 promise 的问题
          // 直到 resolve 的结果既不是 object 也不是 function
          resolvePromise(promise2, value, resolve, reject)
        }, reason => {
          // 这里是错误的回调函数
          // reason 是错误的原因
          // 如果多次调用直接返回
          if (used) return
          // 执行成功回调后，将 used 设置为true，解决多次调用问题
          used = true
          // 执行错误后抛出错误
          // 不需要在判断类型了
          reject(reason)
        })
      } else {
        // then 不是 function 则直接返回 x 作为 promise2 的结果
        resolve(x)
      }
    } catch (e) {
      // 如果出现重复调用直接返回
      if (used) return
      // 进入 catch 也算执行完成
      used = true
      // 把错误通过 reject 返回
      reject(e)
    }
  } else {
    // 其他的所有情况，直接返回 x
    resolve(x)
  }
}

class Promise {
  constructor(executor) {
    // 初始状态
    this.status = 'pending'
    // 初始状态中成功值
    this.value = undefined
    // 初始状态中失败理由
    this.reason = undefined

    // 为了兼容 promise 的多次调用
    // 增加 onFulfilled 的回调函数队列
    this.onFulfilledCallbacks = []
    // 增加 onRejected 的回调函数队列
    this.onRejectedCallbacks = []

    // 定义 resolve 方法，接收 value 并完成赋值
    // 将状态从 pending 改为 fulfilled
    let _resolve = (value) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'fulfilled'
        this.value = value;
        // 在状态变更后执行 onFulfilled 回调函数队列
        this.onFulfilledCallbacks.forEach(fn => fn())
        // 执行完成后清空队列
        this.onFulfilledCallbacks = []
      }
    }
    // 定义 reject 方法，接收 reason 并完成赋值
    // 将状态从 pending 改为 rejected
    let _reject = (reason) => {
      // 状态不为 pending 时不处理
      if (this.status === 'pending') {
        this.status = 'rejected'
        this.reason = reason
        // 在状态变更后执行 onRejected 回调函数队列
        this.onRejectedCallbacks.forEach(fn => fn())
        // 执行完成后清空队列
        this.onRejectedCallbacks = []
      }
    }
    // 执行传入的方法
    try {
      executor(_resolve, _reject)
    } catch (error) {
      // 在 executor 执行失败时调用 reject 方法
      _reject(error)
    }
  }

  // then 接受两个参数 onFulfilled、onRejected
  then(onFulfilled, onRejected) {
    // onFulfilled onRejected 是可选参数
    // 规范要求 onFulfilled onRejected 不能同步调用

    // onFulfilled 如果不是函数，就直接返回value
    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value;
    // onFulfilled 如果不是函数，就直接扔出错误
    // 如果不 throw 错误，而是 value => value
    // 会跑到下一个 then 中的 onFulfilled 中
    onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err };

    // 这里创建 promise2
    // promise2 接收 resolve, reject
    let promise2 = new Promise((resolve, reject) => {
      // 状态为 fulfilled 的时候，执行 onFulfilled 方法，并且传递 value
      if (this.status === 'fulfilled') {
        // 因为要求异步调用，这里采用 setTimeout 的形式异步处理
        setTimeout(() => {
          // 这里声明 x 用于表示 onFulfilled 的返回值
          let x = onFulfilled(this.value)
          // 处理 return 的 promise 和默认的 promise2 的关系
          resolvePromise(promise2, x, resolve, reject)
        }, 0)
      }
      // 状态为 rejected 的时候，执行 onRejected 方法，并且传递 reason
      if (this.status === 'rejected') {
        // 因为要求异步调用，这里采用 setTimeout 的形式异步处理
        setTimeout(() => {
          // 这里声明 x 用于表示 onRejected 的返回值
          let x = onRejected(this.reason)
          // 处理 return 的 promise 和默认的 promise2 的关系
          resolvePromise(promise2, x, resolve, reject)
        }, 0)
      }
      // 为了处理 promise 的异步处理
      // 所以这里将对应的参数全部存入队列中
      // 等 promise 的状态变更时再执行
      // 状态变更就是执行 _reject 和 _resolve 的时候
      if (this.status === 'pending') {
        // onFulfilled 存入 onFulfilledCallbacks 队列
        this.onFulfilledCallbacks.push(() => {
          // 因为要求异步调用，这里采用 setTimeout 的形式异步处理
          setTimeout(() => {
            // 这里声明 x 用于表示 onFulfilled 的返回值
            let x = onFulfilled(this.value)
            // 处理 return 的 promise 和默认的 promise2 的关系
            resolvePromise(promise2, x, resolve, reject)
          }, 0)
        })
        // onRejected 存入 onRejectedCallbacks 队列
        this.onRejectedCallbacks.push(() => {
          // 因为要求异步调用，这里采用 setTimeout 的形式异步处理
          setTimeout(() => {
            // 这里声明 x 用于表示 onRejected 的返回值
            let x = onRejected(this.reason)
            // 处理 return 的 promise 和默认的 promise2 的关系
            resolvePromise(promise2, x, resolve, reject)
          }, 0)
        })
      }
    })
    // then 返回 promise2
    return promise2
  }

  // catch 方法
  // catch 方法实际是 then 的语法糖
  // then 方法中，如果没有提供 onRejected 回调函数
  // 或者 onRejected 回调函数抛出异常
  // JavaScript 引擎会继续查找后面是否有 catch 方法
  // 有则被 catch 方法捕获
  catch(fn) {
    return this.then(null, fn)
  }

  // resolve 方法
  // 静态方法
  // value 是一个 Promise 实例，直接返回
  // 否则返回一个新的 Promise，并使用 resolve 将其兑现
  static resolve(value) {
    if (value instanceof Promise) {
      return value
    }

    return new Promise((resolve) => {
      resolve(value)
    })
  }

  // reject 方法
  // 静态方法
  // 不关心 reason 的类型，直接通过 reject 返回
  static reject(reason) {
    return new Promise((resolve, reject) => {
      reject(reason)
    })
  }

  // finally 方法
  // 也是利用 then 方法实现
  finally(finallyFn) {
    // finally 无论是 resolve 还是 reject 都会执行 finallyFn
    return this.then(
      // 原 Promise 对象 resolve 时
      // 新 Promise 对象会先执行 finallyFn 函数
      // 然后将原 Promise 对象的值作为结果返回
      (value) => {
        Promise.resolve(finallyFn()).then(
          () => value,
          // finallyFn 函数执行时抛出异常，新 Promise 对象会捕获这个异常
          // 并 reject 返回
          (newReason) => { throw newReason }
        )
      },
      // 当原 Promise 对象 reject 时
      // 新 Promise 对象会先执行 finallyFn 函数
      // 然后将原 Promise 对象的 reason 作为结果返回
      (reason) => {
        Promise.resolve(finallyFn()).then(
          () => reason,
          // finallyFn 函数执行时抛出异常，新 Promise 对象会捕获这个异常
          // 并 reject 返回
          (newReason) => { throw newReason }
        )
      }
    )
  }

  // all 方法
  // 全部成功才返回结果
  // 任意报错则返回错误
  static all(values) {
    // values不是一个可迭代对象就报错
    if (typeof values[Symbol.iterator] !== 'function') {
      throw new TypeError('values must be an iterable object.')
    }
    // 返回一个 Promise
    return new Promise((resolve, reject) => {
      // 结果集合
      const results = []
      // 执行计数器
      let count = 0
      // 遍历计数器
      let index = 0
      for (const value of values) {
        // 因为 index 会自增，所以这里先保存下来
        let currentIndex = index
        // 遍历数+1
        index++
        // 执行 Promise.resolve
        Promise.resolve(value).then(
          (value) => {
            // 将结果存储
            results[currentIndex] = value
            // 执行计数器+1
            count++
            // 如果执行计数器和遍历计数器相等，则所有都执行完毕
            // 返回结果集合
            if (count === index) {
              resolve(results)
            }
          },
          // 遇到错误则整个 all 犯法抛出错误
          (reason) => { reject(reason) }
        )
      }
      if (index === 0) {
        resolve(results)
      }
    })
  }

  // any 方法
  // 任意成功则返回结果
  static any(values) {
    // values不是一个可迭代对象就报错
    if (typeof values[Symbol.iterator] !== 'function') {
      throw new TypeError('values must be an iterable object.')
    }
    return new Promise((resolve, reject) => {
      // 结果集合
      const results = []
      // 执行计数器
      let count = 0
      // 遍历计数器
      let index = 0
      for (const value of values) {
        // 因为 index 会自增，所以这里先保存下来
        let currentIndex = index
        // 遍历数+1
        index++
        // 执行 Promise.resolve
        Promise.resolve(value).then(
          // 任意成功则返回结果
          (value) => {
            resolve(value)
          },
          (reason) => {
            // 将原因存储
            results[currentIndex] = reason
            // 执行计数器+1
            count++
            // 如果执行计数器和遍历计数器相等，则所有都执行完毕
            // 返回原因集合
            if (count === index) {
              reject(results)
            }
          }
        )
      }
      // 遍历计数器不变则报错
      if (index === 0) {
        reject(results)
      }
    })
  }

  // race 方法
  // race 方法中 values 里面的 promise 执行过程中第一个返回的 resolve 则成为 race 返回 resolve
  // race 方法中 values 里面的 promise 执行过程中第一个返回的 reject 则成为 race 返回 reject
  static race(values) {
    // values不是一个可迭代对象就报错
    if (typeof values[Symbol.iterator] !== 'function') {
      throw new TypeError('values must be an iterable object.')
    }
    return new Promise((resolve,reject)=>{
      for(const value of values){
        Promise.resolve(value).then(
          (value)=>{ resolve(value) },
          (reason)=>{ reject(reason) }
        );
      }
    })
  }
}

Promise.defer = Promise.deferred = function () {
  let dfd = {}
  dfd.promise = new Promise((resolve,reject)=>{
    dfd.resolve = resolve;
    dfd.reject = reject;
  });
  return dfd;
}
module.exports = Promise;

```

```js
// 有点遗憾
// 上述代码有部分 promise/A+ 规范没通过，等待下次修复
```
